#!/bin/bash

msg='Enter your choice'
options=("Setup new Simulation" "Run Simulation" "Analyze Results" "Visualize Results")

echo $msg
select opt in "${options[@]}"
do
case $opt in
	"Setup new Simulation")
		"ps/new_sim"
		;;
	"Run Simulation")
		"ps/run_sim"
		;;
	"Analyze Results")
		"ps/anl_sim"
		;;
	"Visualize Results")
		"ps/vis_sim"
		;;
	*)
		echo "invalid in"
		;;
esac
done
