#!/bin/bash

echo "Select Simulation State Directory:"
./ps/directory_select "base/states/" 1
SIM_PATH="$( cat coms.txt )"
SIM="$( basename $SIM_PATH )"
echo "Selected File: $SIM_PATH"

echo "Select Simulation State Directory:"
./ps/directory_select $SIM_PATH 1
STATE_PATH="$( cat coms.txt )"
echo "Selected File: $STATE_PATH"

mkdir ${STATE_PATH}/data

echo "Select Analysis Command:"
options=("Gmx Energy" "Gmx Density" "Gyration Radius" "Polystat")
select opt in "${options[@]}"
do
case $opt in
	"Gmx Energy")
		gmx energy -f ${STATE_PATH}/${SIM}.edr -o ${STATE_PATH}/data/${SIM}_energy
		;;
	"Gmx Density")
		gmx density -f ${STATE_PATH}/${SIM}.xtc -s ${STATE_PATH}/${SIM}.tpr -o ${STATE_PATH}/data/${SIM}_density
		;;
	"Gyration Radius")
		gmx gyrate -f ${STATE_PATH}/${SIM}.xtc -s ${STATE_PATH}/${SIM}.tpr -o ${STATE_PATH}/data/${SIM}_gyrate
		;;
	"Polystat")
		gmx polystat -f ${STATE_PATH}/${SIM}.xtc -s ${STATE_PATH}/${SIM}.tpr -o ${STATE_PATH}/data/${SIM}_polystat
		;;
	*)
		echo "invalid in"
		;;
esac
done
