#!/bin/bash

DIR=$1
EXT=$2
echo ">> Select $EXT file from $DIR:"
options=( $(find $DIR -name "*$EXT") )

select opt in "${options[@]}" "Quit" ; do 
    if (( REPLY == 1 + ${#options[@]} )) ; then
        exit

    elif (( REPLY > 0 && REPLY <= ${#options[@]} )) ; then
        echo  "$opt" > coms.txt
        break

    else
        echo "Invalid option."
    fi
done
