#!/bin/bash


echo "Select Simulation State Directory:"
./ps/directory_select "base/states/" 1
SIM_PATH="$( cat coms.txt )"
SIM="$( basename $SIM_PATH )"
echo "Selected FIle: $SIM_PATH"

echo "Select Simulation State Directory:"
./ps/directory_select $SIM_PATH 1
STATE_PATH="$( cat coms.txt )"
echo "Selected FIle: $STATE_PATH"

./ps/file_select "base/procs/" ".mdp"
PROC="$( cat coms.txt )"
echo "Selected FIle: $PROC"

echo "Enter New State Name:"
read NEW_STATE

mkdir ${SIM_PATH}/${NEW_STATE}
mkdir ${SIM_PATH}/${NEW_STATE}/bin


gmx grompp -maxwarn 2 -f $PROC -c ${STATE_PATH}/${SIM}.gro -p ${SIM_PATH}/topol.top -o ${STATE_PATH}/bin/run.tpr

#Copy over topol.top
cp ${SIM_PATH}/topol.top ${STATE_PATH}/bin/topol.top

gmx mdrun -v -deffnm ${STATE_PATH}/bin/run


#Move over results
#touch ${SIM_PATH}/${NEW_STATE}/${SIM}.edr
mv ${STATE_PATH}/bin/run.edr ${SIM_PATH}/${NEW_STATE}/${SIM}.edr
#touch ${NEW_STATE}/${SIM}.gro
mv ${STATE_PATH}/bin/run.gro ${SIM_PATH}/${NEW_STATE}/${SIM}.gro
#touch ${NEW_STATE}/${SIM}.trr
mv ${STATE_PATH}/bin/run.trr ${SIM_PATH}/${NEW_STATE}/${SIM}.trr
#touch ${NEW_STATE}/${SIM}.xtc
mv ${STATE_PATH}/bin/run.xtc ${SIM_PATH}/${NEW_STATE}/${SIM}.xtc
#touch ${NEW_STATE}/${SIM}.tpr
cp ${STATE_PATH}/bin/run.tpr ${SIM_PATH}/${NEW_STATE}/${SIM}.tpr



