#!/bin/bash

./ps/directory_select "base/states/" 1
SIM_PATH="$( cat coms.txt )"
SIM="$( basename $SIM_PATH )"
./ps/directory_select $SIM_PATH 1
STATE_PATH="$( cat coms.txt )"

echo "Run what?"
options=("Xmgrace Energy" "Xmgrace Density" "Vdm State" "Vdm Movie")
select opt in "${options[@]}"
do
case $opt in
	"Vdm State")
		vmd ${STATE_PATH}/${SIM}.gro
		;;
	"Vdm Movie")
		vmd ${STATE_PATH}/${SIM}.gro ${STATE_PATH}/${SIM}.xtc
		;;
	"Xmgrace Energy")
		xmgrace ${STATE_PATH}/data/${SIM}_energy.xvg
		;;
	"Xmgrace Density")
		xmgrace ${STATE_PATH}/data/${SIM}_density.xvg
		;;
	*)
		echo "invalid in"
		;;
esac
done
